### PR TITLE
fix: remove scrollbar

### PR DESCRIPTION
**Pull request by hyoban**
before

ScreenShot 2024-01-08 16 38 31

after

ScreenShot 2024-01-08 16 39 09

### CODE REVIEW

**Comment by aksharahegde** [comment]
not sure. but it would be good to set `overflow-auto` so that by default scrollbar wont appear but will be useful if content overflows.

**Comment by hyoban** [comment]
Yes, but I don't know where this card needs to be scrolled.

**Comment by himself65** [comment]
> Yes, but I don't know where this card needs to be scrolled.

there is a case: you can try https://npm-stat.link/vue?count=100

**Review by himself65 — APPROVED** [review]
I will merge for now since it will fix the scrollbar, but It will break the case https://npm-stat.link/vue?count=100 or similar

**Pull request merged**
