### PR TITLE
feat(help): put the "count" and "sort" search params in footer

### PR DESCRIPTION
**Pull request by Haroenv**
requires #7, otherwise doesn't really make sense to document it

### CODE REVIEW

**Review by himself65 — CHANGES_REQUESTED** [review]
I will hold this for now. since there are some issues with CSS

**Review by himself65 — COMMENTED** [review]
I think dont put into footer. But into the buttom of the search bar

**Comment by Haroenv** [comment]
Put it on the home page now, feel free to make changes on your side, not fully sure where it should go @himself65

**Comment by himself65** [comment]
I will check when I have time

**Comment by himself65** [comment]
I am too tired today, merge it tomorrow

**Comment by himself65** [comment]
Working on this

**Review by himself65 — APPROVED** [review]

**Pull request merged**
