### PR TITLE
fix: handle longer content

### PR DESCRIPTION
**Pull request by hyoban**
continue #3 

appearance

generated image

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
looks promising

**Comment by himself65** [comment]
example: https://npm-download-stat-git-fork-hyoban-main-alex-yang.vercel.app/react?count=1000

**Review by himself65 — COMMENTED** [review]
UI will be blocked when you click `copy image` button. I guess there is some performance issue when we modify the style. Is there any possibles we move to another thread?(like into web worker or server-side?)

**Comment by hyoban** [comment]
Maybe blocking the UI is acceptable here? Generally, we will not set a very large count, otherwise the generated image will become very long.

**Pull request merged**
