### PR TITLE
feat(versionRollout): add semver sort option

### PR DESCRIPTION
**Pull request by Haroenv**
if you put `?sort=semver`, the versions will be shown based on semver version, not based on download count

### CODE REVIEW

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
Geat idea

**Review by himself65 — COMMENTED** [review]
Could you please merge the conflicts?

**Comment by Haroenv** [comment]
Thanks, fixed the merge conflict @himself65

**Review by himself65 — CHANGES_REQUESTED** [review]
No, hold on. The large version should be on the top?

image

**Comment by Haroenv** [comment]
good catch @himself65, seems like in some rebase I ended up with a reverse sort by accident

**Review by himself65 — APPROVED** [review]

**Pull request merged**
